---
language: node_js
node_js:
  - "4"

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install -g yarn@0.16.1
  - yarn install
  - bower install

before_script:
  - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3

script:
  - ./node_modules/.bin/ember try:each

