---
language: node_js
node_js:
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  # absurdly, yarn reliably fails on the first try and succeeds on the second here.
  - until yarn install --non-interactive; do echo "trying yarn again"; done

script:
  - yarn lint:hbs
  - yarn lint:js
  - yarn test
